### ISSUE TITLE
Package version in npm registry

### ISSUE THREAD

**Issue by makkaronis4e** [moribvndvs/ng2-idle#177]
Hi! Can you please publish latest version to npm?

<img width="954" alt="image" src="https://user-images.githubusercontent.com/33792090/204117045-d3d4e7d0-a580-4ac4-99c7-9dbf5c890372.png">

**Comment by omostan** [comment]
First of all, I would like to commend your team for the great work on this library.

It will be much appreciated if someone from your team kindly releases the latest v12.0.0 to npm, as @makkaronis4e requested in November 2022. The publshed v11.1.0 is compiled with Angular "View Engine" instead of Ivy. Compatibility for the view engine has since been removed from later Angular versions.

Please update the code and publish the latest version on npm.

Thank you very much!

**Comment by psarno** [comment]
I assume v12 will fix this?

> 'NgIdleKeepaliveModule' does not appear to be an NgModule class.(-996002)
> module.d.ts(2, 15): This likely means that the library (@ng-idle/keepalive) which declares NgIdleKeepaliveModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
