### ISSUE TITLE
Add support for Angular 17

### ISSUE THREAD

**Issue by dsubelman** [moribvndvs/ng2-idle#195]
### **Desired functionality**

Add support for Angular 17 release.

Now that Angular 17 has been released, are there any plans to release a new version that supports Angular 17?

**Comment by robinprieschl** [comment]
Are currently any plans for this? It is currently blocking us from upgrading to Angular 17 for our project.

**Comment by dmitrye** [comment]
This needs to be upgraded because Angular 17/18 apps not using Zone.js break with "Zone is not defined" due to direct reference in ng-idle-core on line 750 for example.

**Comment by hey24sheep** [comment]
@moribvndvs Hi, can we please add the support for Angular version 17 & 18. That will be great, we have our project updated to 18 recently and we are currently in build fail due to this package being unsupported :(

**Comment by BhuiyanSaif18** [comment]
Hi @hey24sheep there are two active PRs for [Angular 17](https://github.com/moribvndvs/ng2-idle/pull/200) and [Angular 18](https://github.com/moribvndvs/ng2-idle/pull/201) Can you review the PR whether it works and meets the requirements?

**Comment by hey24sheep** [comment]
@BhuiyanSaif18 I just reviewed they are migrations only. So, it should work but the release needs to happen through the owner so it can be published on NPM itself. This issue has been open since 2023, I think it's high time to update the packages to support 17 & 18. I request for the update, it is very much needed to upgrade our projects. I don't want to maintain the forks just for the project upgrade.

**Comment by AHaseebAwan** [comment]
@moribvndvs do you think, we could merge these PRs mentiond by @BhuiyanSaif18? LGTM!

**Comment by moribvndvs** [comment]
Closed by #200
